# Site settings
name: Brooke Watson
description: "Infectious Disease Epidemiologist"
url: "http://brooklyneveryone.github.io/" 


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  brooklyneveryone 
# facebook_username: your_facebook_username_goes_here 
twitter_username: brookLYNevery1 
linkedin_username: brookewatson1
instagram_username:  brooklyneveryone 
medium_username:  brooklyneveryone 
blog_url: "/newsletter"
# email: "/newsletter"


avatar: yes
avatar_img_path: "imgs/avatar.png"
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
# avatar_img_path: "https://avatars2.githubusercontent.com/u/17301305"


front_img: yes
front_img_path: "imgs/gili t.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
